name: example
description:
  Example demonstrating how to use the library directed_graph.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  directed_graph:
    path: ../
  ansicolor: ^1.0.2
  graphs: ^0.2.0
