name: directed_graph

description:
  Directed graph with algorithms enabling topological ordering and sorting
  of vertices.

version: 0.1.4

homepage: https://github.com/simphotonics/directed_graph

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  graphs: ^0.2.0
  lazy_evaluation: ^0.0.6+3
  meta: ^1.1.8

dev_dependencies:
  test: ^1.14.7
