name: directed_graph

description:
  Directed graph with topological sorting methods.

version: 0.0.1

homepage: https://github.com/simphotonics/directed_graph

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  graphs: ^0.2.0
  lazy_evaluation: ^0.0.6+3

dev_dependencies:
  test: ^1.11.0
