name: directed_graph

description: Directed graph with algorithms enabling topological ordering and
  sorting of vertices. The package provides a graph crawler for finding the
  paths connecting two vertices.

version: 0.2.2

homepage: https://github.com/simphotonics/directed_graph

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  graphs: ^0.2.0
  lazy_evaluation: ^0.0.6+3
  meta: ^1.2.2

dev_dependencies:
  ansicolor: ^1.0.2
  benchmark_harness: ^1.0.5
  pedantic: ^1.9.2
  test: ^1.15.3
