name: directed_graph

description: Directed graph with algorithms enabling topological ordering and
  sorting of vertices. The package provides a graph crawler for finding the
  paths connecting two vertices.

version: 0.3.0

homepage: https://github.com/simphotonics/directed_graph

environment:
  sdk: '>=2.12.0-29.7.beta <3.0.0'

dependencies:
  #graphs: ^0.2.0
  #collection: ^1.14.13

dev_dependencies:
  benchmark_harness: ^1.0.5
  pedantic: ^1.9.2
  test: 1.16.0-nullsafety.10


dependency_overrides:
  # ansicolor:
  #   git:
  #     url: git://github.com/simphotonics/ansicolor-dart.git
  #     ref: null_safety
  benchmark_harness:
    git:
      url: git://github.com/dart-lang/benchmark_harness.git
      ref: null_safety
  # lazy_evaluation:
  #   git:
  #     url: git://github.com/simphotonics/lazy_evaluation.git
  #     ref: null_safety
