name: performance
description:
  Benchmark of directed_graph utility functions.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  benchmark_harness: ^1.0.5
  directed_graph:
    path: ../
  meta: ^1.2.1
  graphs: ^0.2.0
