name: performance
description:
  Benchmark of directed_graph utility functions.


environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  directed_graph:
    path: ../
  benchmark_harness: ^1.0.5
  ansicolor: ^1.0.2
  graphs: ^0.2.0
